version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/example.conf:/etc/nginx/sites-available/example.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mongo
    networks:
      - mongodb
    
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb

volumes:
  mongodb_data:

networks:
  mongodb:

