apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name {{ .Values.nginx.serverName }};

        index index.php register.php submit.php;

        error_log {{ .Values.nginx.errorLog }};
        access_log {{ .Values.nginx.accessLog }};
        root {{ .Values.nginx.root }};

        rewrite ^/(.*)/$ /$1 permanent; 

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php/php{{ .Values.nginx.phpVersion }}-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_buffering off;
        }
    }
