# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Release.Name }}-mongodb-pvc
#   labels:
#     app: {{ .Release.Name }}-mongodb
# spec:
#   accessModes:
#     {{- toYaml .Values.persistence.accessModes | nindent 4 }}
#   resources:
#     requests:
#       storage: {{ .Values.persistence.size }}
#   storageClassName: {{ .Values.persistence.storageClass | quote }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
  labels:
    app: {{ .Release.Name }}-mongodb
spec:
  {{- if .Values.persistence.enabled }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi 
  {{- end }}
